using System.Text;
using FluentAssertions;
using FsCheck;
using FsCheck.Xunit;
using VSoftSol.Syslog.Core.Enums;
using VSoftSol.Syslog.Core.Events;
using VSoftSol.Syslog.Ingestion;
using VSoftSol.Syslog.Ingestion.Parsing;
using Xunit;

namespace VSoftSol.Syslog.UnitTests.Parsing;

/// <summary>
/// PHASE_03 property-based: "for any generated byte sequence: the parser never throws,
/// never hangs, always returns a result, and raw_message is always byte-identical to the
/// input. Run 10,000 cases minimum."
/// </summary>
[Trait("Category", "Parsing")]
public sealed class ParserPropertyTests
{
    private static readonly MessageParser Parser = ParsingComposition.Build().Parser;
    private static readonly DateTimeOffset Received = new(2026, 3, 1, 12, 0, 0, TimeSpan.Zero);

    private static RawFrame Frame(byte[] payload) =>
        new(Received, "203.0.113.10", "udp:test", Protocol.Udp, payload, truncated: false);

    [Property(MaxTest = 12_000, EndSize = 4_000)]
    public Property Parse_ForAnyByteSequence_NeverThrows_AlwaysReturns_RawIsByteIdentical()
    {
        return Prop.ForAll(Arb.Default.Array<byte>(), bytes =>
        {
            bytes ??= [];
            SyslogEvent e = Parser.Parse(Frame(bytes));

            return e.RawMessage.ToArray().SequenceEqual(bytes)
                   && e.SourceIp == "203.0.113.10"
                   && e.ReceivedUtc == Received
                   && Enum.IsDefined(e.ParseStatus);
        });
    }

    [Property(MaxTest = 10_000)]
    public Property Parse_ForAnyPrintableString_NeverThrows_AndRoundTripsRawBytes()
    {
        return Prop.ForAll(Arb.Default.String(), s =>
        {
            byte[] bytes = Encoding.UTF8.GetBytes(s ?? string.Empty);
            SyslogEvent e = Parser.Parse(Frame(bytes));
            return e.RawMessage.ToArray().SequenceEqual(bytes);
        });
    }

    [Property(MaxTest = 5_000)]
    public Property Parse_AnyString_CompletesQuickly()
    {
        return Prop.ForAll(Arb.Default.String(), s =>
        {
            var sw = System.Diagnostics.Stopwatch.StartNew();
            _ = Parser.Parse(Frame(Encoding.UTF8.GetBytes(s ?? string.Empty)));
            sw.Stop();
            return sw.Elapsed < TimeSpan.FromSeconds(2);
        });
    }

    [Fact]
    public void Parse_TenThousandRandomFrames_AllPreserveRawBytes_NoException()
    {
        var rng = new System.Random(20260906);
        for (int i = 0; i < 10_000; i++)
        {
            byte[] bytes = new byte[rng.Next(0, 600)];
            rng.NextBytes(bytes);
            SyslogEvent e = Parser.Parse(Frame(bytes));
            e.RawMessage.ToArray().Should().Equal(bytes);
        }
    }
}
