-- Migration 010 — v1.1: MFA login-flow enforcement (B11-3).
-- Forward-only, one transaction (MigrationRunner).

------------------------------------------------------------------------------
-- A short-lived, single-use challenge issued between a successful password check
-- and a successful second-factor check, for an account with mfa_enabled = 1. The
-- token is the row's own primary key (opaque, generated by the application, never
-- guessable) rather than an auto-increment id, so it can be carried in a hidden form
-- field without exposing a sequential identifier. Deleted on success, on exceeding
-- attempts_made, or opportunistically when expired (SqliteMfaLoginChallengeStore).
------------------------------------------------------------------------------
CREATE TABLE mfa_login_challenges (
    challenge_token  TEXT PRIMARY KEY,
    user_id          INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    attempts_made    INTEGER NOT NULL DEFAULT 0,
    created_utc      TEXT NOT NULL,
    expires_utc      TEXT NOT NULL
);
CREATE INDEX ix_mfa_login_challenges_user ON mfa_login_challenges (user_id);
